### ISSUE TITLE
Fix sizing of bottom row of member logos 

### ISSUE THREAD

**Issue by danamlewis** [TCNCoalition/website#26] opened 2020-04-09 18:54 UTC
Top row correctly contextualized size to each other, bottom row varying sizes:

![image](https://user-images.githubusercontent.com/7468165/78930378-da83c180-7a58-11ea-9bfb-8625864c607c.png)

**Comment by kreativmonkey** [comment] 2020-04-09 21:17
there is no size to fix, in the members file i describe the correct size of the logo but not everyone read this information...

**Comment by dijour** [comment] 2020-04-10 16:03
I think the correct way to do this would be to account for it in CSS... trying to wrangle every different member to properly submit PNGs is tough.

**Comment by kreativmonkey** [comment] 2020-04-10 17:10
Not really. I know it will work with css, but I think we should prefer the right size, because it will make the file size for downloading/displaying much smaller! But i will have a look at this later on.

**Comment by dijour** [comment] 2020-04-10 17:11
Do you currently allow SVG? That would solve a lot of problems.

**Comment by harperreed** [comment] 2020-04-13 19:57
SVG would be best.

**Comment by dijour** [comment] 2020-04-13 20:14
> SVG would be best.

Of course! Let's please standardize if possible. Would make our images look much better across a range of devices, as well as load faster. Even opens up the possibility of SVG animations, if we want to get fancy 😄

**Comment by kreativmonkey** [comment] 2020-04-13 22:13
Yes SVG is nice, but SVG need to implement in a different way to normal image files. 

We can do it with the switch in the mebres.yml like:

```yaml
- organization: ito
  country: Germany
  logo: images/members/ito-logo.svg
  svg: true
  url: https://www.ito-app.org/
```

ore

```yaml
- organization: ito
  country: Germany
  logo: 
     png: images/members/ito-logo.png
     svg: images/members/ito-logo.svg
  url: https://www.ito-app.org/
```

ore 

```yaml
- organization: ito
  country: Germany
  logo: images/members/ito-logo.png
  svg-logo: image/members/ito-logo.svg
  url: https://www.ito-app.org/
```
```yaml
- organization: ito
  country: Germany
  logo: 
    file: images/members/ito-logo.png
    type: svg
  url: https://www.ito-app.org/
```

i don't know wich is the best....

**Comment by kreativmonkey** [comment] 2020-04-13 22:53
I found another solution...

```
 {{ path.Ext "a/b/c/news.html" }} → ".html"
```
i check the path extension for svg so i can switch between object and img tag. 

https://github.com/TCNCoalition/website/commit/ce426ae7dd7ed566e018d76a60646a019a010c07

The only reason why you want a png/jpg is for fallback if the browser dosn't support the SVG.

**Comment by harperreed** [comment] 2020-04-13 23:09
I think you can just put svg in an IMG tag

**Comment by dijour** [comment] 2020-04-14 02:26
Yeah lol ^

**Comment by kreativmonkey** [comment] 2020-04-14 08:06
Off course @harperreed but you got some limitations while doing so!

https://vecta.io/blog/best-way-to-embed-svg#comparison

If we want to use the img tag, then the problem is solved with the current implementation and no further work is required.

**Comment by harperreed** [comment] 2020-04-14 13:11
yea. let's just use the img tag. 

The linked article is very good. Thanks for linking it. Their recommendation despite limitations is to also use the img tag.

**Comment by kreativmonkey** [comment] 2020-04-14 14:31
I think we can close this issue because the image tag is aelrady there and can be used for svg. You can see a test with the ito svg logo on my commit 1bc85a7 above.

**Comment by harperreed** [comment] 2020-04-14 14:33
wfm. closing

**Closed as completed by harperreed** 2020-04-14 14:33 UTC
